<?php
/* @var $this ClientsController */
/* @var $model Clients */

/*$this->breadcrumbs=array(
	'Clients'=>array('index'),
	$model->name,
);
*/
$this->menu=array(
	array('label'=>'List Clients', 'url'=>array('index')),
	array('label'=>'Create Clients', 'url'=>array('create')),
	array('label'=>'Update Clients', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete Clients', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Clients', 'url'=>array('admin')),
);
?>

<h1>View Clients #<?php echo $model->id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'name',
		'nick',
		'address',
		'postalcode',
		'nric',
		'birthdate',
		'nationality',
		'res_tel',
		'ofc_tel',
		'mobile',
		'email',
		'company',
		'designation',
		'drvlicense_passdate',
		'policy_id',
		'v_model',
		'v_type',
		'engine_cap',
		'yr_manufactured',
		'reg_date',
		'roadTax_expDate',
		'carPlate',
		'oldVehcNo',
		'insuranceCo',
		'oldNCD',
		'prevExpDate',
		'covPolicyNo',
		'covCoverNoteNo',
		'covCoverageType',
		'covPlan',
		'covGrossPrem',
		'covNCD',
		'covExcess',
		'covWindScrAmnt',
		'covLoadAmnt',
		'covPersonalAcc',
		'covExtension',
		'covSurCharge',
		'covPassLiab',
		'covOther1',
		'covOther2',
		'covOther3',
		'covLoyaltyDis',
		'covNoClaim',
		'covNCDProtectr',
		'covCommDate',
		'covExpDate',
		'covInsurCo',
		'covTermDate',
		'spNameBroker',
		'spAnnualPrem',
		'spDiscount',
		'spPremDue',
		'spGST',
		'spMiscChanges',
		'spTotalDue',
		'spComm1',
		'spNetUnderwriter',
		'spFirmComm',
		'spAgentComm',
		'spEarnings',
		'spRemarks',
		'spPaymentBy',
		'spReceiptNo',
		'dpDrverName',
		'dpDrverICno',
		'dpDrverOcc',
		'dpDateBirth',
		'dpDrverLcnsePass',
		'dpDrverMarStat',
		'dpGender',
		'dpRelationship',
		'dpNationality',
		'dpWage',
		'dpRemarks',
		'dpRef',
		'dpMonth',
	),
)); ?>
